import secrets
from typing import TypeAlias
import math

"""
Winternitz signature paramaters and auxiliary values
See page 8 https://cic.iacr.org/p/2/2/24/pdf

n can be 128 or 256
w can be 1, 2, 4 or 8
"""
n = 128
w = 8
a = n / w
c = math.log(a * (pow(2, w) - 1), 2) / w


"""
Contains the secret/private keys generated by function Gen 
See page 9 https://cic.iacr.org/p/2/2/24/pdf
"""
CSK: TypeAlias = list[list[int]]


"""
Contains a path from a PK to the root of the Merkle tree, where each node is a KeyID
See page 11 and 12 https://cic.iacr.org/p/2/2/24/pdf
"""
PATH: TypeAlias = list[bytes | int]
PK: TypeAlias = bytes

class CPK:
    ROOT: any


class CRV:
    R: any 
    CHK: any
    PATH: any
    SK: any


def randomBits(bits: int = n):
    return secrets.randbits(bits)