import secrets
from typing import TypeAlias
import math

"""
Winternitz signature paramaters and auxiliary values
See page 8 https://cic.iacr.org/p/2/2/24/pdf

n can be 128 or 256
w can be 1, 2, 4 or 8
"""
N = 128
N_BYTES = N // 8
W = 8
A = N // W
C = math.ceil(math.log2(A * (2**W - 1)) / W)
CHAIN_LEN = 2**W


"""
Contains the secret/private keys generated by function Gen 
See page 9 https://cic.iacr.org/p/2/2/24/pdf
"""
CSK: TypeAlias = list[list[int]]


"""
Contains a path from a PK to the root of the Merkle tree, where each node is a KeyID
See page 11 and 12 https://cic.iacr.org/p/2/2/24/pdf
"""
PATH: TypeAlias = list[bytes | int]
PK: TypeAlias = bytes


"""
Contains a list of signing coalition lists, where each element in the sublist is an integer
corresponding to a trustee. The list is indexed by KeyID
See page 23 https://cic.iacr.org/p/2/2/24/pdf
"""
CL: TypeAlias = list[list[int]]

class CPK:
    ROOT: any


class CRV:
    R: any 
    CHK: any
    PATH: any
    SK: any


def randomBits(bits: int = N):
    return secrets.randbits(bits)